INSERT INTO cities(name) VALUES
('Albuquerque'),
('Arlington'),
('Atlanta'),
('Austin'),
('Baltimore'),
('Boston'),
('Charlotte'),
('Chicago'),
('Cleveland'),
('Colorado Springs'),
('Columbus'),
('Dallas'),
('Detroit'),
('Denver'),
('El Paso'),
('Fort Worth'),
('Fresno'),
('Houston'),
('Indianapolis'),
('Jacksonville'),
('Kansas City'),
('Las Vegas'),
('Long Beach'),
('Los Angeles'),
('Memphis'),
('Mesa'),
('Miami'),
('Milwaukee'),
('Minneapolis'),
('Nashville-Davidson'),
('New Orleans'),
('New York'),
('Oakland'),
('Oklahoma City'),
('Omaha'),
('Philadelphia'),
('Phoenix'),
('Portland'),
('Raleigh'),
('Sacramento'),
('San Antonio'),
('San Diego'),
('San Jose'),
('San Francisco'),
('Seattle'),
('Tucson'),
('Tulsa'),
('Virginia Beach'),
('Washington'),
('Wichita');
